import { Inter } from 'next/font/google'
import './globals.scss'
import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Header />

        <main>
          {children}

          <div className="wrapperImg">
            <Image src='/Rectangle.png' width={559} height={415} alt='Rectangle' loading="eager" priority="high" />
            <h1>Welcome</h1>
            <p>Just Smile</p>
          </div>
        </main>

        <Footer />
      </body>
    </html>
  )
}
